"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export function DocumentUploader({ companies, userId }: { companies:{id:string;name:string}[]; userId:string }) {
  const router=useRouter(); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");setMessage("");const fd=new FormData(e.currentTarget);const companyId=String(fd.get("company_id")||"");const file=fd.get("file") as File | null;if(!companyId||!file||!file.size){setError("Seleziona azienda e file");setBusy(false);return;}const supabase=createClient();const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${companyId}/${crypto.randomUUID()}-${safe}`;const {error:uploadError}=await supabase.storage.from("farm-documents").upload(path,file,{upsert:false});if(uploadError){setError(uploadError.message);setBusy(false);return;}const {error:dbError}=await supabase.from("documents").insert({company_id:companyId,category:String(fd.get("category")||"ALTRO"),file_name:file.name,storage_path:path,mime_type:file.type||null,document_date:String(fd.get("document_date")||"")||null,notes:String(fd.get("notes")||"")||null,uploaded_by:userId});if(dbError){await supabase.storage.from("farm-documents").remove([path]);setError(dbError.message);setBusy(false);return;}setMessage("Documento caricato");(e.currentTarget as HTMLFormElement).reset();router.refresh();setBusy(false);}
  return <form onSubmit={submit} className="form-grid cols-2"><label>Azienda<select name="company_id" required><option value="">Seleziona</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Categoria<select name="category"><option>RICETTA_TRATTAMENTO</option><option>ETICHETTA</option><option>DDT_ACQUISTO</option><option>ANALISI</option><option>CERTIFICAZIONE</option><option>FOTO</option><option>ALTRO</option></select></label><label>Data documento<input type="date" name="document_date" /></label><label>File PDF / immagine<input type="file" name="file" accept="application/pdf,image/jpeg,image/png,image/webp" required /></label><label className="span-2">Note<input name="notes" /></label>{error&&<div className="alert error span-2">{error}</div>}{message&&<div className="alert success span-2">{message}</div>}<button className="btn primary span-2" disabled={busy}>{busy?"Caricamento…":"Carica documento"}</button></form>;
}
