import { createEquipmentAction, createTaskAction, setCompanyAccessAction, setUserRoleAction, updateProfileAction } from "@/app/actions";
import { createCropAction, createSupplierAction } from "@/app/settings-actions";
import { Feedback, PageHeader } from "@/components/app-shell";
import { requireProfile } from "@/lib/auth";
import { fmtDate } from "@/lib/utils";

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ok?:string;error?:string}> }) {
  const {supabase,profile}=await requireProfile(); const params=await searchParams;
  const [companiesQ,equipmentQ,suppliersQ,cropsQ,profilesQ,membersQ,tasksQ]=await Promise.all([
    supabase.from("companies").select("id,name").eq("active",true).order("name"),
    supabase.from("equipment").select("*,companies(name)").order("name"),
    supabase.from("suppliers").select("*,companies(name)").order("name"),
    supabase.from("crops").select("*").order("name"),
    supabase.from("profiles").select("id,full_name,phone,role,active").order("full_name"),
    supabase.from("company_users").select("company_id,user_id"),
    supabase.from("tasks").select("id,title,due_at,status,assigned_to,profiles!tasks_assigned_to_fkey(full_name),companies(name)").order("created_at",{ascending:false}).limit(30),
  ]);
  const companies=companiesQ.data??[], equipment=equipmentQ.data??[], suppliers=suppliersQ.data??[], crops=cropsQ.data??[], profiles=profilesQ.data??[], memberships=membersQ.data??[], tasks=tasksQ.data??[];
  return <>
    <PageHeader eyebrow="CONFIGURAZIONE" title="Impostazioni operative" description="Profilo, utenti, accessi aziendali, attrezzature, fornitori, colture e attività assegnate." />
    <Feedback ok={params.ok} error={params.error} />
    <section className="panel" style={{marginBottom:18}}><div className="section-head"><div><p className="eyebrow">PROFILO</p><h2>Il tuo account · {profile.role}</h2></div></div><form action={updateProfileAction} className="form-grid cols-3"><label>Nome e cognome<input name="full_name" defaultValue={profile.full_name??""} /></label><label>Telefono<input name="phone" defaultValue={profile.phone??""} /></label><div style={{alignSelf:"end"}}><button className="btn primary">Aggiorna profilo</button></div></form></section>
    {profile.role==="ADMIN"&&<>
      <div className="two-col" style={{marginBottom:18}}>
        <section className="panel"><div className="section-head"><div><p className="eyebrow">UTENTI</p><h2>Ruoli e aziende</h2></div></div><div className="stack">{profiles.map((u:any)=><div className="card" key={u.id}><div className="section-head" style={{marginBottom:10}}><div><strong>{u.full_name??u.id.slice(0,8)}</strong><p className="muted" style={{margin:3}}>{u.phone??"Nessun telefono"}</p></div><span className={u.role==="ADMIN"?"role admin":"role"}>{u.role}</span></div><div className="actions-row"><form action={setUserRoleAction} style={{display:"flex",gap:6}}><input type="hidden" name="user_id" value={u.id}/><select name="role" defaultValue={u.role}><option>OPERATOR</option><option>ADMIN</option></select><button className="btn small">Ruolo</button></form></div><div className="legend" style={{marginTop:10}}>{companies.map((c:any)=>{const on=memberships.some((m:any)=>m.user_id===u.id&&m.company_id===c.id);return <form action={setCompanyAccessAction} key={c.id}><input type="hidden" name="user_id" value={u.id}/><input type="hidden" name="company_id" value={c.id}/><input type="hidden" name="operation" value={on?"revoke":"grant"}/><button className={`btn small ${on?"accent":""}`}>{on?"✓ ":"+ "}{c.name}</button></form>})}</div></div>)}</div></section>
        <section className="panel"><div className="section-head"><div><p className="eyebrow">ATTIVITÀ OPERATORI</p><h2>Assegna compito</h2></div></div><form action={createTaskAction} className="form-grid cols-2"><label className="span-2">Titolo<input name="title" required /></label><label>Azienda<select name="company_id"><option value="">Generale</option>{companies.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Assegna a<select name="assigned_to"><option value="">Non assegnato</option>{profiles.map((u:any)=><option key={u.id} value={u.id}>{u.full_name??u.id.slice(0,8)}</option>)}</select></label><label>Scadenza<input name="due_at" type="datetime-local" /></label><label>Descrizione<input name="description" /></label><button className="btn primary span-2">Crea attività</button></form><div className="list" style={{marginTop:15}}>{tasks.slice(0,8).map((t:any)=><div className="list-item" key={t.id}><div><strong>{t.title}</strong><p>{t.profiles?.full_name??"Non assegnato"} · {t.companies?.name??"Generale"}</p></div><span className="badge">{t.due_at?fmtDate(t.due_at.slice(0,10)):"—"}</span></div>)}</div></section>
      </div>
      <div className="three-col">
        <section className="panel"><div className="section-head"><div><p className="eyebrow">ATTREZZATURE</p><h2>Botti e mezzi</h2></div></div><div className="list">{equipment.slice(0,6).map((e:any)=><div className="list-item" key={e.id}><div><strong>{e.name}</strong><p>{[e.brand,e.model,e.capacity_l&&`${e.capacity_l} L`].filter(Boolean).join(" · ")}</p></div></div>)}</div><form action={createEquipmentAction} className="stack" style={{marginTop:15}}><label>Nome<input name="name" required /></label><label>Tipo<input name="equipment_type" required placeholder="Botte, trattore…" /></label><div className="form-grid cols-2"><label>Marca<input name="brand" /></label><label>Modello<input name="model" /></label><label>Capacità L<input type="number" name="capacity_l" /></label><label>Costo €/h<input type="number" step="0.01" name="hourly_cost" /></label></div><label>Azienda<select name="company_id"><option value="">Condivisa</option>{companies.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="btn primary">Aggiungi</button></form></section>
        <section className="panel"><div className="section-head"><div><p className="eyebrow">FORNITORI</p><h2>Anagrafiche</h2></div></div><div className="list">{suppliers.slice(0,6).map((s:any)=><div className="list-item" key={s.id}><div><strong>{s.name}</strong><p>{s.companies?.name??"Condiviso"}</p></div></div>)}</div><form action={createSupplierAction} className="stack" style={{marginTop:15}}><label>Nome<input name="name" required /></label><label>Azienda<select name="company_id"><option value="">Condiviso</option>{companies.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>P. IVA<input name="vat_number" /></label><label>Email<input type="email" name="email" /></label><label>Telefono<input name="phone" /></label><button className="btn primary">Aggiungi</button></form></section>
        <section className="panel"><div className="section-head"><div><p className="eyebrow">COLTURE</p><h2>Catalogo</h2></div></div><div className="list">{crops.slice(0,10).map((c:any)=><div className="list-item" key={c.id}><div><strong>{c.name}</strong><p>{c.kind}{c.eppo_code?` · ${c.eppo_code}`:""}</p></div></div>)}</div><form action={createCropAction} className="stack" style={{marginTop:15}}><label>Nome<input name="name" required /></label><label>Tipo<select name="kind"><option>ANNUALE</option><option>PLURIENNALE</option></select></label><label>Codice EPPO<input name="eppo_code" /></label><button className="btn primary">Aggiungi</button></form></section>
      </div>
    </>}
  </>;
}
